POST API for user.
vinodkadam02/SpringBootApplication pull request #1
Opened 2022-12-29 12:21 UTC by ashutosh2406

2022-12-29 12:33 UTC, mh-scarmel commented on src/main/java/com/elixr/poc/rest/validator/UserValidator.java
> +        if (newUserRequest.getFirstName() == null || newUserRequest.getFirstName().isEmpty()) {
You can use StringUtils.isBlank(newUserRequest.getFirstName())  it will check for both null and empty.Do the same for all validation

2022-12-30 04:38 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/validator/UserValidator.java
> +        if (newUserRequest.getFirstName() == null || newUserRequest.getFirstName().isEmpty()) {
Updated and using StringUtils.isBlank() for validation.

2023-01-02 06:45 UTC, mh-spunnappala requested changes

2023-01-02 06:45 UTC, mh-spunnappala commented on build.gradle
> +	testAnnotationProcessor 'org.projectlombok:lombok:1.18.24'
Please make sure three Gradle configuration is required for the Lombok dependency
1. implementation 'org.projectlombok:lombok:1.18.24'
2. compileOnly 'org.projectlombok:lombok:1.18.24'
3. annotationProcessor 'org.projectlombok:lombok:1.18.24'

2023-01-02 06:45 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/constant/ErrorConstants.java
> +public class ErrorConstants {
It is good to declare a private constructor to avoid instantiating the constant class.

2023-01-02 06:45 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserCreationController.java
> +public class UserCreationController {
I would suggest renaming this controller class to UserController if you are planning to add other methods like patching and getting users in the future.

2023-01-02 06:45 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserCreationController.java
> +    @Autowired
Constructor-based dependency injection is better than field-based dependency injection. Please change accordingly

2023-01-02 06:45 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserCreationController.java
> +        return UserService.builder().build().editResponse(newUser);
Why are you using the UserService builder to call the editResponse method, even if you have autowired the userService?

2023-01-02 06:45 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserCreationController.java
> +        return UserService.builder().build().editResponse(newUser);
I would suggest renaming the editResponse method to createUser. I think the purpose of the editResponse method is to create the user right?

2023-01-02 06:45 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/service/UserService.java
> +@Builder
@Builder annotation is not required to use in the service layer class. Remove the @Builder annotation and try to run your application.

2023-01-02 06:45 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/service/UserService.java
> +        List<String> errorList = UserValidator.builder().build().validate(userRequestObject);
I would suggest using spring boot validation framework to validate incoming request

2023-01-02 06:45 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/service/UserService.java
> +        if (!errorList.isEmpty()) {
I would suggest using the apache commons ObjectUtils.isNotEmpty() method instead of this not-empty checking. So the code will be more readable.

2023-01-02 07:45 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/controller/UserCreationController.java
> +        return UserService.builder().build().editResponse(newUser);
Actually the purpose of editResponse is to edit the response which we are sending after geting the request.

2023-01-02 07:45 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/service/UserService.java
> +@Builder
I have removed @builder from service class.

2023-01-02 07:46 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/controller/UserCreationController.java
> +    @Autowired
Now I am using constructor based injection.

2023-01-02 07:47 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/controller/UserCreationController.java
> +public class UserCreationController {
Changed class name to UserController.

2023-01-02 07:55 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/constant/ErrorConstants.java
> +public class ErrorConstants {
Now I have declared the private constructor to avoid instantiating the constant class.

2023-01-02 08:14 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/service/UserService.java
> +        if (!errorList.isEmpty()) {
Now I am using ObjectsUtils.isNotEmpty().

2023-01-02 08:55 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/rest/controller/UserCreationController.java
> +public class UserCreationController {
No, We are planning to have separate controller classes for Patch & Delete so that merging process is smooth.

2023-01-03 06:55 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/service/UserService.java
> +        List<String> errorList = UserValidator.builder().build().validate(userRequestObject);
Now I am using spring boot validation framework for validation

2023-01-04 03:33 UTC, mh-sraveendran approved these changes

2023-01-04 03:34 UTC, mh-sraveendran approved these changes

2023-01-04 07:54 UTC, mh-spunnappala requested changes

2023-01-04 07:54 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/constant/ErrorConstants.java
> +public class ErrorConstants {
you can use lombok @NoArgsConstructor annotation with AccessLevel.PRIVATE instead of private constructor block of code

2023-01-04 07:54 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/response/ExceptionHandler.java
> +Handling the exception and sending propper error message
Please correct the typo in word propper

2023-01-04 07:54 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/response/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler(MethodArgumentNotValidException.class)
The class name and the annotation name are the same, that is why you have to provide the class name with the package. So rename this class and change it accordingly

2023-01-04 07:54 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/response/ExceptionHandler.java
> +    private ErrorResponse errorResponse;
This instance variable is not needed here, you can directly declare in your method

2023-01-04 07:54 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/response/ExceptionHandler.java
> +    public ResponseEntity<?> myMessage(MethodArgumentNotValidException methodArgumentNotValidException) {
You can give the method name more readable like handleMethodArgumentNotValid

2023-01-04 07:54 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/response/ExceptionHandler.java
> +        return getResponseEntity(methodArgumentNotValidException);
This private method call is not needed here. you can directly keep the code inside this method itself

2023-01-04 07:54 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/response/ErrorResponse.java
> +    private List<String> errorMessage;
I would suggest introducing a FieldError object and which should contain two attributes like fieldName and errorMessage. So that the end user can identify the corresponding error to the attribute.

2023-01-04 07:54 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/service/UserService.java
> +    public UserService(UserRepository saveDataToRepository) {
Please rename this UserRepository object to a meaningful name, because this object can be used to call delete, update, etc. You can rename it to just userRepository.

2023-01-04 07:54 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/service/UserService.java
> +        return user;
Immediately return this expression instead of assigning a local variable and then return

2023-01-04 07:54 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/service/UserService.java
> +    public UserResponse sendResponse(UserRequest userRequestObject) {
Rename the method to a meaningful name, the purpose of the method seems like create a user

2023-01-04 07:54 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/constant/ErrorConstants.java
> +
Remove this empty line

2023-01-04 07:54 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/data/User.java
> +
Remove this empty line

2023-01-04 07:54 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/response/ExceptionHandler.java
> +
Remove all empty lines like this from all files. Can keep one empty line for code readability, but multiple empty lines are not recommended

2023-01-04 07:54 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/service/UserService.java
> +    /*
Recommended comment format is /** */

2023-01-04 09:24 UTC, ashutosh2406 commented on build.gradle
> +	testAnnotationProcessor 'org.projectlombok:lombok:1.18.24'
I removed the additional one

2023-01-04 09:25 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/constant/ErrorConstants.java
> +public class ErrorConstants {
I am using @NoArgsConstructor with AccessLevel.PRIVATE.

2023-01-04 09:41 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/response/ExceptionHandler.java
> +Handling the exception and sending propper error message
Corrected the type of documentation

2023-01-04 09:48 UTC, EXR-86 commented on src/main/java/com/elixr/poc/service/UserService.java
> +    /*
using this recommended format

2023-01-04 09:48 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/response/ExceptionHandler.java
> +
removed all empty lines

2023-01-04 09:48 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/data/User.java
> +
removed the empty lines

2023-01-04 09:48 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/constant/ErrorConstants.java
> +
Removed the empty lines and formatted propperly

2023-01-04 09:48 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/service/UserService.java
> +    public UserResponse sendResponse(UserRequest userRequestObject) {
changed the method name to createValidUser.

2023-01-04 09:48 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/response/ExceptionHandler.java
> +    public ResponseEntity<?> myMessage(MethodArgumentNotValidException methodArgumentNotValidException) {
changed the method name.

2023-01-04 09:48 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/response/ExceptionHandler.java
> +    private ErrorResponse errorResponse;
Now I take it as local variable

2023-01-04 09:48 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/response/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler(MethodArgumentNotValidException.class)
Changed the class name to

2023-01-04 10:08 UTC, mh-spunnappala approved these changes

2023-01-04 11:39 UTC, merged