Feature get all users v1
vinodkadam02/SpringBootApplication pull request #10
Opened 2023-01-06 09:01 UTC by ashutosh2406

2023-01-17 05:31 UTC, mh-ppremlatha requested changes

2023-01-17 05:31 UTC, mh-ppremlatha commented on src/main/java/com/elixr/poc/rest/response/GetAllResponse.java
>  public class GetAllResponse extends AppResponse {
```suggestion
public class GetAllUsersResponse extends AppResponse {
```

2023-01-17 05:31 UTC, mh-ppremlatha commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +    public GetAllResponse getAllUser() {
Please make sure both methods in the controller follow the same pattern. So it would be better to return a ResponseEntity<GetAllUsersResponse> here as well.

2023-01-17 05:31 UTC, mh-ppremlatha commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
>          return new ResponseEntity<>(userResponse, HttpStatus.OK);
You should handle not found cases too

2023-01-17 05:33 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/response/GetAllResponse.java
>  public class GetAllResponse extends AppResponse {
As This class is being used by people who are working on purchase so I named it as GetAllRespnse

2023-01-17 05:35 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
>          return new ResponseEntity<>(userResponse, HttpStatus.OK);
It is getting handled by GlobalExceptionHandler class

2023-01-17 07:06 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +    public GetAllResponse getAllUser() {
Now all the methods of controller class are in similar pattern

2023-01-18 04:01 UTC, mh-sraveendran approved these changes

2023-01-18 05:23 UTC, mh-spunnappala requested changes
Resolve the build errors in the branch as well

2023-01-18 05:23 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/service/UserService.java
> +     * Retriving all the users
Resolve the typo

2023-01-18 05:53 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/service/UserService.java
> +     * Retriving all the users
Solved the typo

2023-01-18 06:04 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/service/UserService.java
> +     * Retriving all the users
Solved the build errors

2023-01-18 07:08 UTC, mh-spunnappala approved these changes

2023-01-18 08:26 UTC, merged