Raised Pr for Get Purchase by Id
vinodkadam02/SpringBootApplication pull request #12
Opened 2023-01-09 06:38 UTC by vivekhit2000

2023-01-09 08:35 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/rest/controller/PurchaseRetrievalController.java
> +            PurchaseResponse purchaseResponse = PurchaseResponse.purchaseBuilder().success(true).id(purchase.getId()).userName(purchase.getUserName()).product(purchase.getProduct()).amount(purchase.g
formatting not proper

2023-01-09 08:35 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/rest/response/PurchaseGetResponse.java
> +
Missing documentation

2023-01-09 09:11 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/rest/response/PurchaseGetResponse.java
> +
Updated.

2023-01-09 09:11 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/rest/controller/PurchaseRetrievalController.java
> +            PurchaseResponse purchaseResponse = PurchaseResponse.purchaseBuilder().success(true).id(purchase.getId()).userName(purchase.getUserName()).product(purchase.getProduct()).amount(purchase.g
Updated.

2023-01-10 05:03 UTC, kssreejith1994 requested changes

2023-01-10 05:03 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/constants/ApplicationConstants.java
> +    public static final String BLANK_ID = "The ID is blank";
A general comment-when you define enums or constants, it should be defined in Alphabetical order.

2023-01-10 05:03 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/exception/GlobalException.java
> +public class GlobalException extends Exception {
The exception name should be relevant to the application you are building or specific to the functionality you are implementing. For example if this is for purchase, you can create a PurchaseException which extends Runtime Exception class. This would allow you to throw this exception wherever you intentionally throws an exception.

2023-01-10 05:03 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(commonErrorResponse, HttpStatus.BAD_REQUEST);
Are all un handled exceptions bad request?

2023-01-10 05:03 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/rest/controller/PurchaseRetrievalController.java
> +    public ResponseEntity retrievePurchase(@PathVariable("purchaseId") @Valid UUID purchaseId) throws GlobalException {
Every line of this method is enclosed inside try block. So, do we really need this throws statement?

2023-01-10 05:03 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/rest/response/PurchaseGetResponse.java
> +        setSuccess(success);
If you are using the success attribute to indicate status of a request, then I would suggest you to rename the abstract class to something like Response or AppResponse etc.

2023-01-10 05:03 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/rest/response/PurchaseResponse.java
> +    @Id
Could you please let me know why Id is added here?

2023-01-10 05:03 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/rest/response/PurchaseResponse.java
> +    @Id
And I believe this is a data object?

2023-01-10 05:03 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/rest/response/PurchaseGetResponse.java
> +public class PurchaseGetResponse extends ErrorResponse {
Where is PurchaseGetResponse used?

2023-01-10 06:35 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/constants/ApplicationConstants.java
> +    public static final String BLANK_ID = "The ID is blank";
OK, updated.

2023-01-10 06:35 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/exception/GlobalException.java
> +public class GlobalException extends Exception {
I extended to RunTimeException, And the reason behind GlobalException is actually this is used by user and purchase.

2023-01-10 06:35 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(commonErrorResponse, HttpStatus.BAD_REQUEST);
No at all, I updated some request as NOT_FOUND as per the requirement.

2023-01-10 06:35 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/rest/controller/PurchaseRetrievalController.java
> +    public ResponseEntity retrievePurchase(@PathVariable("purchaseId") @Valid UUID purchaseId) throws GlobalException {
No we don't need this,  I removed.

2023-01-10 06:35 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/rest/response/PurchaseGetResponse.java
> +        setSuccess(success);
Updated

2023-01-10 06:35 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/rest/response/PurchaseResponse.java
> +    @Id
@ID is not required here, so i removed this.

2023-01-10 06:35 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/rest/response/PurchaseGetResponse.java
> +public class PurchaseGetResponse extends ErrorResponse {
OK, so by mistake, i Commit this PurchaseGetResponse, Actually we need this in some othe API.

2023-01-10 08:05 UTC, mh-spillai requested changes

2023-01-10 08:05 UTC, mh-spillai commented on src/main/java/com/elixr/poc/constants/ApplicationConstants.java
> -    public static final String USER_NAME_MISSING = "Username is mandatory";
It's better to add validation messages in the message.properties file.

2023-01-11 05:14 UTC, mh-spunnappala requested changes

2023-01-11 05:14 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +        return purchase.orElseThrow(() -> new GlobalException(ApplicationConstants.ID_MISMATCH));
The error message should match the use case.

2023-01-11 09:07 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/rest/response/PurchaseGetResponse.java
> +public class PurchaseGetResponse extends ErrorResponse {
Updated

2023-01-11 09:08 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/constants/ApplicationConstants.java
> -    public static final String USER_NAME_MISSING = "Username is mandatory";
Updated

2023-01-11 09:08 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +        return purchase.orElseThrow(() -> new GlobalException(ApplicationConstants.ID_MISMATCH));
Updated

2023-01-11 10:17 UTC, kssreejith1994 approved these changes

2023-01-16 07:15 UTC, mh-sraveendran approved these changes

2023-01-16 12:45 UTC, merged