get user by username
vinodkadam02/SpringBootApplication pull request #13
Opened 2023-01-11 09:31 UTC by ashutosh2406

2023-01-11 13:45 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +            return new ResponseEntity(UserResponse.builder().success(true).id(user.getId()).userName(user.getUserName()).firstName(user.getFirstName()).lastName(user.getLastName()).build(), HttpStatu
Check the presence of the user by making a method in UserService class say "getUser(username)"itself and make it return the UserResponse object . If the UserResponse object is not present, make it return a custom exception class NotFoundException.java

The reason for my ask is that the controller should only call the service method and if that service method throws any exception, the spring framework will take the responsibiltiy of routing the appropriate response status codes according to configured exceptions in GlobalExceptionHandler class.

My next comment will give more details on this

2023-01-11 13:51 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +            return new ResponseEntity<>(CommonResponse.builder().success(false).errorMessage(MessagesUtil.getMessage(MessagesKeyEnum.ENTITY_USER_NOT_EXISTS.getKey())).build(), HttpStatus.NOT_FOUND);
In GlobalExceptionHandler class, please make a seperate " @ExceptionHandler(NotFound.class) and make it return 404 Not found HttpStatus Code

2023-01-11 14:59 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/service/UserService.java
>              success = true;
I don't see success variable used anywhere in the method after you initialized to true . This method is directly returning true after the else part and so you can remove this success variable.

2023-01-11 15:09 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/service/UserService.java
> +            saveDataToDatabase(user);
Please rename the method to "saveUser" because the entity you are saving here is user. As a standard, use the particular name of the entity used in that scenario after save when naming the save method. We dont need the word "toDatabase" in the name because that is understood by default that destination will be database. If you are saving to some excel file or something , then you can use the name like "saveUserToExcel"

2023-01-11 15:09 UTC, mh-saicharanvelury requested changes
Gave some comments

2023-01-16 08:32 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +            return new ResponseEntity(UserResponse.builder().success(true).id(user.getId()).userName(user.getUserName()).firstName(user.getFirstName()).lastName(user.getLastName()).build(), HttpStatu
I Understood your comment and changed as per it

2023-01-16 08:33 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +            return new ResponseEntity<>(CommonResponse.builder().success(false).errorMessage(MessagesUtil.getMessage(MessagesKeyEnum.ENTITY_USER_NOT_EXISTS.getKey())).build(), HttpStatus.NOT_FOUND);
Removed that else part and handling exception by spring boot

2023-01-16 08:34 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/service/UserService.java
>              success = true;
removed the unusual declaration of variable success

2023-01-16 08:34 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/service/UserService.java
> +            saveDataToDatabase(user);
renamed to saveUser

2023-01-16 08:40 UTC, mh-sraveendran approved these changes

2023-01-17 05:40 UTC, mh-ppremlatha requested changes

2023-01-17 05:40 UTC, mh-ppremlatha commented on src/main/java/com/elixr/poc/data/User.java
> +import java.util.List;
Unwanted import

2023-01-17 05:40 UTC, mh-ppremlatha commented on src/main/java/com/elixr/poc/repository/UserRepository.java
> +import java.util.List;
Is this import needed?

2023-01-17 05:40 UTC, mh-ppremlatha commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
>  @RequestMapping("/application")
Do you need this /application path? I don't think it matches the requirements

2023-01-17 05:40 UTC, mh-ppremlatha commented on src/main/java/com/elixr/poc/rest/response/UserResponse.java
> +import org.springframework.web.ErrorResponse;
Where is this import being used?

2023-01-17 05:40 UTC, mh-ppremlatha commented on src/main/java/com/elixr/poc/service/UserService.java
> +            saveUser(user);
Not using the return value of this method

2023-01-17 05:40 UTC, mh-ppremlatha commented on src/main/java/com/elixr/poc/service/UserService.java
> +            return UserResponse.builder().success(true).id(user.getId()).userName(user.getUserName()).firstName(user.getFirstName()).lastName(user.getLastName()).build();
What if the request does not contain an id, and it is randomly generated by the code? Will you get the value for user.getId() here since you are not using the return value of the saveUser() method?

2023-01-17 05:40 UTC, mh-ppremlatha commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +        return new ResponseEntity<>(userService.getUserByName(userName), HttpStatus.OK);
Follow similar pattern for methods in the controller, here the service class is returning the response object, however in the above method, the controller class is building the response object. Please make them similar.

2023-01-17 06:16 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/service/UserService.java
> +            return UserResponse.builder().success(true).id(user.getId()).userName(user.getUserName()).firstName(user.getFirstName()).lastName(user.getLastName()).build();
Yes I am getting the value of user.getId() as I am updating the value of user.setId() in saveUser().

2023-01-17 06:19 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/service/UserService.java
> +            saveUser(user);
No I am not using the return value of that method because as I am updating the value of user.setId() at saveUser() and while using user.getId() it will directly give the updated id value.

2023-01-17 06:58 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/data/User.java
> +import java.util.List;
removed unwanted imports

2023-01-17 06:58 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/repository/UserRepository.java
> +import java.util.List;
No I removed it

2023-01-17 06:59 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
>  @RequestMapping("/application")
As it is not in requirement we removed that path

2023-01-17 06:59 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/response/UserResponse.java
> +import org.springframework.web.ErrorResponse;
removed all unwanted imports

2023-01-17 07:01 UTC, ashutosh2406 commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +        return new ResponseEntity<>(userService.getUserByName(userName), HttpStatus.OK);
As the above method is done by Vinod  and as he got comment from Shiju to return response on that pattern so now all the methods have changed to similar pattern

2023-01-18 04:01 UTC, mh-sraveendran approved these changes

2023-01-18 06:20 UTC, merged