Update User by userId
vinodkadam02/SpringBootApplication pull request #14
Opened 2023-01-11 10:55 UTC by vinodkadam02

2023-01-11 11:56 UTC, kssreejith1994 requested changes

2023-01-11 11:56 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/common/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(commonResponse, HttpStatus.BAD_REQUEST);
Create a scenario that throws internal server error and check the status code returned from server in postman. Please let me know the result here

2023-01-11 11:56 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/common/util/MessagesUtil.java
> +            moduleMessagesResourceBundle = null;
Why is the same file present in Divya's PR too? You all are working on different features right? And here a catch without log or rethrown exception should never be used.

2023-01-11 11:56 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(commonErrorResponse, HttpStatus.BAD_REQUEST);
Check for internal server error mentioned earlier here as well

2023-01-11 11:56 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/rest/controller/UserModificationController.java
> +        HttpStatus httpStatus = HttpStatus.OK;
Return the httpstatus directly. Do not store it in another reference variable

2023-01-11 11:56 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/service/UserService.java
> +        return user.orElseThrow(() -> new IdNotFoundException(MessagesUtil.getMessage(MessagesKeyEnum.ENTITY_ID_DOES_NOT_EXISTS.getKey())));
Please explain how does this line work

2023-01-11 11:56 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/util/PropertiesUtil.java
> +@Log4j2
Why is this annotation? Why not slf4j? What is the difference?

2023-01-11 11:56 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/util/PropertiesUtil.java
> +    private static final String PATH = "/messages.properties";
Check how properties files can be loaded using configuration class in spring boot.https://www.baeldung.com/configuration-properties-in-spring-boot

2023-01-11 11:56 UTC, kssreejith1994 commented on src/main/resources/messages.properties
> +entity.user.exists = User already exists.
Add new line.

2023-01-16 11:13 UTC, vinodkadam02 commented on src/main/resources/messages.properties
> +entity.user.exists = User already exists.
Updated

2023-01-16 11:13 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/util/PropertiesUtil.java
> +    private static final String PATH = "/messages.properties";
Updated

2023-01-16 11:13 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/util/PropertiesUtil.java
> +@Log4j2
Solved

2023-01-16 11:13 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/rest/controller/UserModificationController.java
> +        HttpStatus httpStatus = HttpStatus.OK;
Updated

2023-01-16 11:14 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/common/util/MessagesUtil.java
> +            moduleMessagesResourceBundle = null;
Solved

2023-01-17 07:06 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/service/UserService.java
> +        return user.orElseThrow(() -> new IdNotFoundException(MessagesUtil.getMessage(MessagesKeyEnum.ENTITY_ID_DOES_NOT_EXISTS.getKey())));
Searching the user in db by its userId, if user is present with the particular userId then returning the user, if user is not found then throwing an exception IdNotFoundException

2023-01-18 04:01 UTC, mh-sraveendran approved these changes

2023-01-18 12:23 UTC, merged