Upload CSV file
vinodkadam02/SpringBootApplication pull request #21
Opened 2023-03-13 11:43 UTC by vinodkadam02

2023-03-14 09:21 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/common/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler
You may have to add extension exception class name in bracket after @ExceptionHandler like "@ExceptionHandler(ExtensionException.class)" . This will tell if resource throws this exception, it will be treated like BAD REQUEST as mentioned here

2023-03-14 09:24 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/common/MessagesKeyEnum.java
> +    ENTITY_FILE_UPLOADED_SUCCESSFULLY("entity.file.uploaded.successfully"),
As a convention , we will try to have all fields in the enum in alphabetical order so that it will be easy to review and detect these fields later. I think ENTITY_FILE_UPLOADED_SUCCESSFULLY should go up. My feeling do another check and try to make all the fields in this file in alphabetical order

2023-03-14 09:27 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/common/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler
Updated.

2023-03-14 09:28 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/common/MessagesKeyEnum.java
> +    ENTITY_FILE_UPLOADED_SUCCESSFULLY("entity.file.uploaded.successfully"),
Updated.

2023-03-14 09:28 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/bulkipmort/service/FileUploadService.java
> +        return true;
I am not questioning the logic here but I see you are simply returning true without doing any upload logic. If this is the requirement given to you then you can ignore this comment but if you feel that you have missed to write the file upload logic to some location in the laptop, then you can do it here.

2023-03-14 09:29 UTC, mh-saicharanvelury requested changes
Some comments. I will add more if I find any. Meanwhile you may resolve them

2023-03-14 09:30 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/bulkipmort/service/FileUploadService.java
> +        return true;
Yes, the logic part is still in Progress.
I'm trying to read the file and so on

2023-03-14 09:33 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/bulkipmort/service/FileUploadService.java
> +        return true;
Ok. then I will approve after you complete and I finish reviewing that logic.

2023-03-14 09:37 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/common/MessagesKeyEnum.java
> +    ENTITY_FILE_UPLOADED_SUCCESSFULLY("entity.file.uploaded.successfully"),
I see still the lines 15 and 16 are not in alphabetical order. They need to be swapped. Work patiently on the feedbacks after carefully observing all fields before giving it for re-review

2023-03-28 13:36 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/bulkimport/rest/controller/DoctorCreateController.java
> +    public ResponseEntity createDoctor(@RequestBody @Valid Doctor doctor) {
I feel it is not recommended to make Doctor which is a collection  object as a request body because suppose tommorow suppose you are asked to hide one field say patients list from showing in API response, then you cant put @JsonIgnore on it because putting the same will prevent inserting the list into the database . So make a different pojo like "Doctor" with same properties under "rest/data" folder and use that in Rest controller response

2023-03-28 13:38 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/bulkimport/service/DoctorService.java
> +        doctorRepository.save(doctor);
Based on my previous comment, you have to build the Doctor object from rest/data/Doctor object here if you are taking cognizance of my previous comment

2023-03-28 13:43 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/bulkimport/dto/Patient.java
> +    private List<String> doctorId;
Name this field as doctorList. When you say doctor id , it seems to indicate a single element and not the list

2023-03-28 13:51 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/bulkimport/service/reader/FileReader.java
> +                    int headerCount = 0;
Name it as currentHeaderIndex. HeaderCount gives impression that it is total count of headers in the excel

2023-03-28 14:05 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/bulkimport/service/reader/FileReader.java
> +                        columnHeader.put(Arrays.stream(patientKey).toList().get(headerCount), stringValue);
I think there is a problem in filling this map columnHeader. Suppose there are 3 rows in the excel R1, R2 and R3 where each row has 7 columns defined in your code. as per your code, the columnHeader map will hold the seven column values of 3rd ROW ONLY. The values of first 2 rows will be overriden with third one because in the map key is unique and if there is another value coming for the same key, the second row's patient age value will replace the first row's patient age value and so on.  Check this code once again

2023-03-28 14:12 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/bulkimport/service/reader/FileReader.java
> +        String doctorId = columnHeader.get(FileOperationEnum.DOCTOR_ID.getFileKey());
The doctor id column in the excel  as per your above code is a single doctor id value and not comma separated string with multiple doctor ids. In that case why are you maintaining it as doctorList List<String> instead of a string. I am not sure bout the requirement but just wanted to ask this question

2023-03-28 14:14 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/bulkimport/service/reader/FileReader.java
> +        String doctorId = columnHeader.get(FileOperationEnum.DOCTOR_ID.getFileKey());
The same question which I asked previously on why you are adding it into a list instead of a string applies here too

2023-03-28 14:26 UTC, mh-saicharanvelury approved these changes
Gave few comments

2023-03-28 14:32 UTC, mh-saicharanvelury requested changes
Gave few comments

2023-03-29 04:13 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/bulkimport/dto/Patient.java
> +    private List<String> doctorId;
Updated.

2023-03-29 04:13 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/bulkimport/service/reader/FileReader.java
> +                    int headerCount = 0;
Updated.

2023-03-29 04:13 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/bulkimport/service/reader/FileReader.java
> +        String doctorId = columnHeader.get(FileOperationEnum.DOCTOR_ID.getFileKey());
To store multiple Doctors to an single patient.
To get many to many relation between patient and doctor.
Need to work on reading, comma separated values for doctor column.

2023-03-29 04:13 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/bulkimport/service/reader/FileReader.java
> +        String doctorId = columnHeader.get(FileOperationEnum.DOCTOR_ID.getFileKey());
To store multiple Doctors to an single patient.
To get many to many relation between patient and doctor.
Need to work on reading, comma separated values for doctor column.

2023-03-29 04:24 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/bulkimport/service/DoctorService.java
> +        doctorRepository.save(doctor);
Updated.

2023-03-30 03:57 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/bulkimport/rest/controller/DoctorCreateController.java
> +    public ResponseEntity createDoctor(@RequestBody @Valid Doctor doctor) {
Updated.

2023-04-17 06:23 UTC, merged