Delete API for Purchase by purchaseId
vinodkadam02/SpringBootApplication pull request #4
Opened 2023-01-02 12:01 UTC by DivyaSathyan09

2023-01-02 12:18 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +        try {
Its better to check if entity exists by calling repository.findById(uuid) first.
If not found then display an error message "No matching entity found"

2023-01-03 08:33 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +        if (purchaseRecord) {
Naming of boolean variable is not proper.
better name is "purchaseRecordExists"

2023-01-03 08:33 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/Constant/Constants.java
> +public class Constants {
Rename this class as ApplicationConstants.java

2023-01-03 08:33 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/Constant/Constants.java
> +    public static int REQUEST_VALUE;
Dont put non final variable in Constant file

2023-01-03 08:33 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +            Constants.REQUEST_VALUE = 200;
Wrong way of sending info back to calling class.
Define a variable boolean recordAlreadyExists = false in DeleteResponse class and assign the value to that variable.

2023-01-03 10:41 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +        if (purchaseRecord) {
Updated has suggested.

2023-01-03 10:41 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/Constant/Constants.java
> +public class Constants {
Updated

2023-01-03 10:41 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/Constant/Constants.java
> +    public static int REQUEST_VALUE;
Updated.

2023-01-03 10:41 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +            Constants.REQUEST_VALUE = 200;
Updated has suggested.

2023-01-04 03:35 UTC, mh-sraveendran approved these changes

2023-01-04 07:17 UTC, mh-spillai requested changes

2023-01-04 07:17 UTC, mh-spillai commented on src/main/java/com/elixr/poc/rest/response/DeleteResponse.java
> +    private String messages;
It should be errorMsg. Also, could you use Jackson annotations to exclude parameters and change the parameters' label in the response?

2023-01-04 10:32 UTC, mh-spunnappala requested changes

2023-01-04 10:32 UTC, mh-spunnappala commented on build.gradle
> +}
Add a new line at the end of each file.

2023-01-04 10:32 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/Constant/ApplicationConstants.java
> +/* this constant file holds all the error messages for all the end points */
Recommended comment format is /** */. Modify it in all files

2023-01-04 10:32 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/Repository/PurchaseRepository.java
> +public interface PurchaseRepository extends MongoRepository<com.elixr.poc.data.Purchase, UUID> {
Why the purchase class is imported with package?

2023-01-04 11:13 UTC, DivyaSathyan09 commented on build.gradle
> +}
Added the new line.

2023-01-04 11:13 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/Constant/ApplicationConstants.java
> +/* this constant file holds all the error messages for all the end points */
Updated.

2023-01-04 11:13 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/Repository/PurchaseRepository.java
> +public interface PurchaseRepository extends MongoRepository<com.elixr.poc.data.Purchase, UUID> {
I removed now.

2023-01-04 11:13 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/rest/response/DeleteResponse.java
> +    private String messages;
Updated.

2023-01-05 09:39 UTC, mh-spunnappala approved these changes

2023-01-05 09:40 UTC, merged