User GET API By UserId
vinodkadam02/SpringBootApplication pull request #7
Opened 2023-01-05 09:13 UTC by vinodkadam02

2023-01-06 03:00 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/constants/ApplicationConstants.java
>      public static final String DATE_MISSING_IN_PURCHASE = "Date are mandatory";
grammatical mistake "are"

2023-01-06 03:00 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/constants/ApplicationConstants.java
>      public static final String PRODUCT_NAME_IS_MISSING_IN_PURCHASE = "Product name are mandatory";
grammatical mistake "are"

2023-01-06 03:00 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +     * Printing the user and HttpStatus.
probably this statement is wrong. We are not printing anywhere

2023-01-06 03:07 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/service/UserService.java
> +     *
remove these unwanted empty lines

2023-01-06 04:28 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/constants/ApplicationConstants.java
>      public static final String DATE_MISSING_IN_PURCHASE = "Date are mandatory";
Updated.

2023-01-06 04:28 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/constants/ApplicationConstants.java
>      public static final String PRODUCT_NAME_IS_MISSING_IN_PURCHASE = "Product name are mandatory";
Updated.

2023-01-06 04:29 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/service/UserService.java
> +     *
Removed.

2023-01-09 05:20 UTC, mh-spunnappala requested changes

2023-01-09 05:20 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
>          }
why are you catching throwable?

2023-01-09 05:20 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +            throw new GlobalException(ApplicationConstants.ID_MISMATCH);
Why are you catching the throwable?

2023-01-09 05:35 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
>          }
Replaced with GlobalException.

2023-01-09 05:35 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +            throw new GlobalException(ApplicationConstants.ID_MISMATCH);
Replaced with GlobalException.

2023-01-10 08:00 UTC, mh-scarmel commented on src/main/java/com/elixr/poc/constant/ApplicationConstants.java
> +    public static final String LAST_NAME_MISSING_IN_USER = "Last name is mandatory";
add alphabetic order

2023-01-10 08:01 UTC, mh-scarmel commented on src/main/java/com/elixr/poc/constants/ApplicationConstants.java
> +    public static final String USER_NAME_MISSING = "User name is mandatory";
All constant variable should be aphabetic order

2023-01-10 08:01 UTC, mh-spillai requested changes

2023-01-10 08:01 UTC, mh-spillai commented on src/main/java/com/elixr/poc/constant/ApplicationConstants.java
> +public class ApplicationConstants {
You can move this to message.properties and read it from there. Validation messages should be in the message,.properties.

2023-01-10 08:01 UTC, mh-spillai commented on src/main/java/com/elixr/poc/constants/ApplicationConstants.java
> +
Why two separate constant files?

2023-01-10 08:07 UTC, mh-scarmel commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
> +        CommonErrorResponse commonErrorResponse;
Better to create CommonResponse and  success case not need to add errormessage jues message

2023-01-11 04:52 UTC, mh-saicharanvelury commented on src/main/java/com/elixr/poc/data/User.java
>  /**
Except the same comment line coming one line down compared to previous state, there is no change in this file. You can roll back this back to previous state unless someone has commented on it

2023-01-11 04:58 UTC, mh-saicharanvelury requested changes
Added one comment

2023-01-11 05:10 UTC, mh-spunnappala requested changes

2023-01-11 05:10 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/service/UserService.java
> +            throw new GlobalException(ApplicationConstants.ID_MISMATCH);
Error message not matching with the specific use case. Here the scenario is the id does not exist, not the id mismatch. Also, the GlobalException class is a custom exception class and it is better to rename it to be specific to your application

2023-01-11 05:10 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/service/UserService.java
> +        return user.orElseThrow(() -> new GlobalException(ApplicationConstants.ID_MISMATCH));
The error message should match the use case.

2023-01-11 07:08 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/constant/ApplicationConstants.java
> +    public static final String LAST_NAME_MISSING_IN_USER = "Last name is mandatory";
Updated

2023-01-11 07:08 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/constants/ApplicationConstants.java
> +    public static final String USER_NAME_MISSING = "User name is mandatory";
Updated

2023-01-11 09:40 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/constant/ApplicationConstants.java
> +public class ApplicationConstants {
Updated as per your suggestion

2023-01-11 09:41 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/constants/ApplicationConstants.java
> +
Removed one file

2023-01-11 09:46 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
> +        CommonErrorResponse commonErrorResponse;
Updated the 1st part of the comment, but as per requirement we need to show message as "errorMessage"

2023-01-11 09:48 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/data/User.java
>  /**
Yes the commented lines are the changes made by others, to remove the conflicts I just add that line.

2023-01-11 09:59 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/service/UserService.java
> +            throw new GlobalException(ApplicationConstants.ID_MISMATCH);
Updated as suggested

2023-01-11 09:59 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/service/UserService.java
> +        return user.orElseThrow(() -> new GlobalException(ApplicationConstants.ID_MISMATCH));
Updated

2023-01-12 10:59 UTC, mh-spunnappala requested changes

2023-01-12 10:59 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/common/MessagesKeyEnum.java
> +    public String key;
Lower the visibility of this field

2023-01-12 10:59 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/common/exception/GlobalExceptionHandler.java
> +package com.elixr.poc.common.exception;
Why there are two global exception handler class?

2023-01-12 10:59 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/common/exception/GlobalExceptionHandler.java
> +    private ResponseEntity handleMethodArgumentNotValidException(MethodArgumentNotValidException methodArgumentNotValidException) {
Provide the parameterized type for this generic

2023-01-12 10:59 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/common/exception/GlobalExceptionHandler.java
> +    public ResponseEntity handleGlobalException(IdNotFoundException idNotFoundException) {
Provide the parameterized type for this generic

2023-01-12 10:59 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/common/exception/GlobalExceptionHandler.java
> +    public ResponseEntity handleGenericException(Exception exception) {
Provide the parameterized type for this generic

2023-01-12 10:59 UTC, mh-spunnappala commented on src/main/resources/messages.properties
> +entity.user.exists = User already exists.
Missing new line

2023-01-12 11:29 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/common/MessagesKeyEnum.java
> +    public String key;
Updated.

2023-01-12 11:30 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/common/exception/GlobalExceptionHandler.java
> +package com.elixr.poc.common.exception;
By mistake I committed old file too, I removed the old file

2023-01-12 11:30 UTC, vinodkadam02 commented on src/main/resources/messages.properties
> +entity.user.exists = User already exists.
Updated

2023-01-12 11:36 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/common/exception/GlobalExceptionHandler.java
> +    private ResponseEntity handleMethodArgumentNotValidException(MethodArgumentNotValidException methodArgumentNotValidException) {
Updated.

2023-01-12 11:36 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/common/exception/GlobalExceptionHandler.java
> +    public ResponseEntity handleGlobalException(IdNotFoundException idNotFoundException) {
Updated.

2023-01-13 11:07 UTC, mh-spunnappala requested changes

2023-01-13 11:07 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/common/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<CommonResponse> handleGlobalException(IdNotFoundException idNotFoundException) {
Rename the method to match the use case

2023-01-13 11:07 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
>  import org.springframework.web.bind.annotation.*;
wildcard import not recommended

2023-01-13 11:07 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
>  import java.util.UUID;
Remove unused imports

2023-01-13 11:07 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
>          HttpStatus httpStatus;
Remove this local declaration of HttpStatus, instead directly pass the value

2023-01-13 11:07 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
> +        CommonResponse commonErrorResponse;
Remove this declaration here and assign the value directly

2023-01-13 11:07 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
> -    public ResponseEntity<?> deleteUser(@PathVariable("userId") UUID userId) {
Format the method

2023-01-13 11:07 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +import java.util.UUID;
Remove unused imports

2023-01-13 11:07 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +    public ResponseEntity retrieveUser(@PathVariable("userId") @Valid String userId) {
Format the method

2023-01-13 11:07 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
> +            commonErrorResponse = CommonResponse.builder().success(success)
Why the variable name is like commonErrorResponse even if the process is successful? and why success message is set to errorMessage?

2023-01-13 11:07 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
> -    public ResponseEntity<?> deleteUser(@PathVariable("userId") UUID userId) {
Provide the parameterized tye for this generic

2023-01-13 11:07 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +    public ResponseEntity retrieveUser(@PathVariable("userId") @Valid String userId) {
Provide the parameterized tye for this generic

2023-01-13 11:07 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/service/UserService.java
>      }
Refactor this method, consider the following 
1. early return the exception message if the user not found
2. Can avoid using the success flag

2023-01-16 06:12 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/common/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<CommonResponse> handleGlobalException(IdNotFoundException idNotFoundException) {
Updated.

2023-01-16 06:12 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
>  import org.springframework.web.bind.annotation.*;
Updated.

2023-01-16 06:12 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
> +        CommonResponse commonErrorResponse;
Updated

2023-01-16 06:12 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +    public ResponseEntity retrieveUser(@PathVariable("userId") @Valid String userId) {
Updated

2023-01-16 06:12 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
> +            commonErrorResponse = CommonResponse.builder().success(success)
Solved

2023-01-16 06:12 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
> -    public ResponseEntity<?> deleteUser(@PathVariable("userId") UUID userId) {
Updated

2023-01-16 06:12 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/rest/controller/UserRetrievalController.java
> +    public ResponseEntity retrieveUser(@PathVariable("userId") @Valid String userId) {
Updated

2023-01-16 06:12 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/service/UserService.java
>      }
Updated.

2023-01-16 06:13 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
> -    public ResponseEntity<?> deleteUser(@PathVariable("userId") UUID userId) {
Updated

2023-01-16 06:13 UTC, vinodkadam02 commented on src/main/java/com/elixr/poc/rest/controller/UserDeletionController.java
>  import java.util.UUID;
Updated.

2023-01-16 06:45 UTC, mh-spunnappala approved these changes

2023-01-16 07:00 UTC, mh-spillai approved these changes

2023-01-16 07:05 UTC, merged