Feature post api for purchase
vinodkadam02/SpringBootApplication pull request #8
Opened 2023-01-05 10:33 UTC by vivekhit2000

2023-01-05 10:47 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +    public Purchase saveRepository(Purchase purchase) {
why is this method public

2023-01-05 10:47 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +    public PurchaseResponse createValidPurchase(PurchaseRequest purchaseRequestObject) {
Are you creating another method with name createInvalidPurchase()? 
If not just createPurchase() is a good enough name

2023-01-05 10:55 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +    public PurchaseResponse createValidPurchase(PurchaseRequest purchaseRequestObject) {
Updated

2023-01-05 10:55 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +    public Purchase saveRepository(Purchase purchase) {
I make it private now

2023-01-05 10:59 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +    private static Purchase createPurchaseObjectFromRequest(PurchaseRequest purchaseRequest) {
Why is this method static?

2023-01-05 10:59 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +    private Purchase saveRepository(Purchase purchase) {
saveRepository name suggests you are saving respository object which is wrong.
either rename it as savePurchaseInDB or savePurchase

2023-01-05 10:59 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +        return PurchaseResponse.purchaseBuilder().success(true).id(purchaseObject.getId()).userName(purchaseObject.getUserName()).product(purchaseObject.getProduct()).amount(purchaseObject.getAmount(
Format this line to make readable

2023-01-05 10:59 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +    private static Purchase createPurchaseObjectFromRequest(PurchaseRequest purchaseRequest) {
Service should not know anything about rest objects. 
createPurchaseObjectFromRequest() should be done inside controller and purchase object should be passed

2023-01-05 11:34 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +    private static Purchase createPurchaseObjectFromRequest(PurchaseRequest purchaseRequest) {
Updated

2023-01-05 11:36 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +    private static Purchase createPurchaseObjectFromRequest(PurchaseRequest purchaseRequest) {
removed from static

2023-01-05 11:36 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +    private Purchase saveRepository(Purchase purchase) {
Updated

2023-01-05 11:36 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +        return PurchaseResponse.purchaseBuilder().success(true).id(purchaseObject.getId()).userName(purchaseObject.getUserName()).product(purchaseObject.getProduct()).amount(purchaseObject.getAmount(
updated

2023-01-06 07:11 UTC, mh-spunnappala requested changes

2023-01-06 07:11 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/PurchaseCreationController.java
> +    public ResponseEntity<?> addPurchase(@RequestBody @Valid PurchaseRequest newPurchase) {
Remove usage of wildcard type

2023-01-06 07:11 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/PurchaseCreationController.java
> +        return new ResponseEntity<>(PurchaseResponse.purchaseBuilder().success(true).id(purchase.getId()).userName(purchase.getUserName()).product(purchase.getProduct()).amount(purchase.getAmount()).
format the method

2023-01-06 07:11 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/response/PurchaseResponse.java
> +    @Builder(builderMethodName = "purchaseBuilder")
Use Lombok annotation for all argument constructor

2023-01-06 07:11 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +        this.purchaseRepository = purchaseRepository;
why this assignment

2023-01-06 07:48 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/rest/response/PurchaseResponse.java
> +    @Builder(builderMethodName = "purchaseBuilder")
updated

2023-01-06 07:48 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +        this.purchaseRepository = purchaseRepository;
now, removed it, and changed the return type to void.

2023-01-06 07:48 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/rest/controller/PurchaseCreationController.java
> +        return new ResponseEntity<>(PurchaseResponse.purchaseBuilder().success(true).id(purchase.getId()).userName(purchase.getUserName()).product(purchase.getProduct()).amount(purchase.getAmount()).
formatted.

2023-01-06 07:48 UTC, vivekhit2000 commented on src/main/java/com/elixr/poc/rest/controller/PurchaseCreationController.java
> +    public ResponseEntity<?> addPurchase(@RequestBody @Valid PurchaseRequest newPurchase) {
removed

2023-01-18 07:04 UTC, merged