Updating the purchase details from the database
vinodkadam02/SpringBootApplication pull request #9
Opened 2023-01-05 14:54 UTC by DivyaSathyan09

2023-01-06 03:03 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/rest/controller/PurchaseDeletionController.java
>          } catch (NoRecordFoundException e) {
Follow the same pattern as in DeletionController for handling NoRecordFoundException.
This method just throws that exception. Its handled in GLobalExeptionHandler

2023-01-06 05:39 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/rest/controller/PurchaseDeletionController.java
>          } catch (NoRecordFoundException e) {
Updated.

2023-01-09 08:32 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/rest/controller/PurchaseModificationController.java
> +    public ResponseEntity<Purchase> updateUserPartially(@PathVariable("purchaseId") UUID purchaseId, @RequestBody @Valid Purchase purchaseDetails) throws NoRecordFoundException {
Dont use Purchase class in argument or return type of a Controller.
use PurchaseReuqest & PurchaseResponse. 
do the conversion from request/response object to Purchase object in controller

2023-01-09 08:32 UTC, mh-sraveendran commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +        purchase.setUserName(purchaseDetails.getUserName());
add validation.
throw an error if username  does not exists in user table

2023-01-10 07:14 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/rest/controller/PurchaseModificationController.java
> +    public ResponseEntity<Purchase> updateUserPartially(@PathVariable("purchaseId") UUID purchaseId, @RequestBody @Valid Purchase purchaseDetails) throws NoRecordFoundException {
Updated.

2023-01-10 08:07 UTC, mh-spillai commented on src/main/java/com/elixr/poc/constants/ApplicationConstants.java
> +    public static final String AMOUNT_MISSING_IN_PURCHASE = "Amount is mandatory";
Its better to add validation messages in the message.properties file.

2023-01-11 04:50 UTC, mh-spunnappala requested changes

2023-01-11 04:50 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/rest/controller/PurchaseDeletionController.java
> +        deleteResponse = CommonErrorResponse.builder().success(success).errorMessage(ApplicationConstants.SUCCESSFULLY_DELETED).build();
Why is the response object name as ErrorResponse, even if it is a success? Better to rename the class and attributes of the class, or use another success response class if you have

2023-01-11 04:50 UTC, mh-spunnappala commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +            throw new GlobalException(ApplicationConstants.ID_MISMATCH);
Error message not matching with the specific use case. Here the scenario is the id does not exist, not the id mismatch.

2023-01-11 09:45 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/constants/ApplicationConstants.java
> +    public static final String AMOUNT_MISSING_IN_PURCHASE = "Amount is mandatory";
Updated

2023-01-11 09:45 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/rest/controller/PurchaseDeletionController.java
> +        deleteResponse = CommonErrorResponse.builder().success(success).errorMessage(ApplicationConstants.SUCCESSFULLY_DELETED).build();
Updated has per your suggestion

2023-01-11 09:46 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +            throw new GlobalException(ApplicationConstants.ID_MISMATCH);
Updated

2023-01-11 11:46 UTC, kssreejith1994 requested changes

2023-01-11 11:46 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/common/util/MessagesUtil.java
> +            moduleMessagesResourceBundle = null;
A catch block without an exception rethrowed or no logs should never be used. You will have no way of knowing what is the error in your program.

2023-01-11 11:46 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/common/util/MessagesUtil.java
> +    public static String getMessage(String key, Object... arguments) {
Ca you explain what does Object... means?

2023-01-11 11:46 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(commonResponse, HttpStatus.BAD_REQUEST);
Can you try to create an internal server error scenario and check what is the http response code getting returned? Please post the response you get here.

2023-01-11 11:46 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/rest/request/PurchaseRequest.java
> +public class PurchaseRequest {
How are the error messages handled?

2023-01-11 11:46 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/rest/request/PurchaseRequest.java
> +public class PurchaseRequest {
If the fields are not passed.

2023-01-11 11:46 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/rest/response/CommonResponse.java
> +public class CommonResponse {
What is this response used for? You already have another common response class?

2023-01-11 11:46 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +    public boolean deletePurchaseDetails(UUID purchaseId) throws IdNotFoundException {
You are already handling the IdNotFoundException. Why is it throwed again by the method?

2023-01-11 11:46 UTC, kssreejith1994 commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +        Purchase purchase = purchaseRepository.findById(purchaseId).orElseThrow(() -> new IdNotFoundException("Purchase not found on :: " + purchaseId));
Please explain how does this line work?

2023-01-17 06:29 UTC, mh-ppremlatha requested changes

2023-01-17 06:29 UTC, mh-ppremlatha commented on src/main/java/com/elixr/poc/rest/controller/PurchaseDeletionController.java
> +@RequestMapping("/controller")
Why do you have /controller in the path? It does not match the requirement

2023-01-17 06:29 UTC, mh-ppremlatha commented on src/main/java/com/elixr/poc/rest/controller/PurchaseDeletionController.java
> +                .errorMessage(MessagesUtil.getMessage(MessagesKeyEnum.ENTITY_DELETED_SUCCESSFULLY.getKey())).build();
Why are you passing success message in the 'errorMessage' field?

2023-01-17 06:29 UTC, mh-ppremlatha commented on src/main/java/com/elixr/poc/rest/controller/PurchaseModificationController.java
> +@RequestMapping("/controller")
Why do you have /controller in the path? It does not match the requirement

2023-01-17 06:29 UTC, mh-ppremlatha commented on src/main/java/com/elixr/poc/rest/response/CommonResponse.java
>      private String errorMessage;
Why do you need this field here? You have a CommonErrorMessage class with errorMessage field?

2023-01-17 06:48 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/common/util/MessagesUtil.java
> +            moduleMessagesResourceBundle = null;
Updated.

2023-01-17 06:48 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/rest/response/CommonResponse.java
> +public class CommonResponse {
Made changes.

2023-01-17 06:48 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +    public boolean deletePurchaseDetails(UUID purchaseId) throws IdNotFoundException {
Removed

2023-01-17 06:48 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/rest/controller/PurchaseDeletionController.java
> +@RequestMapping("/controller")
Removed.

2023-01-17 06:48 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/rest/controller/PurchaseDeletionController.java
> +                .errorMessage(MessagesUtil.getMessage(MessagesKeyEnum.ENTITY_DELETED_SUCCESSFULLY.getKey())).build();
Updated

2023-01-17 06:48 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/rest/controller/PurchaseModificationController.java
> +@RequestMapping("/controller")
Removed.

2023-01-17 06:49 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/rest/response/CommonResponse.java
>      private String errorMessage;
Updated.

2023-01-17 06:49 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/common/util/MessagesUtil.java
> +    public static String getMessage(String key, Object... arguments) {
Object... is used for multiple arguments to be passed.

2023-01-17 06:50 UTC, DivyaSathyan09 commented on src/main/java/com/elixr/poc/service/PurchaseService.java
> +        purchase.setUserName(purchaseDetails.getUserName());
Updated.

2023-01-18 04:01 UTC, mh-sraveendran approved these changes

2023-01-18 06:33 UTC, merged